name: Weekly Twitter Sentiment Report

on:
  schedule:
    # every Monday at 08:30 UTC
    - cron: '30 8 * * MON'
  workflow_dispatch:        # manual “Run workflow” button

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      # 1 — Checkout repository
      - uses: actions/checkout@v4

      # 2 — System libraries required by some R packages + pagedown
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ghostscript \
            libssl-dev libxml2-dev libcurl4-openssl-dev \
            libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev \
            libpng-dev libtiff5-dev

      # 3 — Set up R
      - uses: r-lib/actions/setup-r@v2

      # 4 — Run the weekly pipeline
      - name: Run weekly sentiment script
        env:
          SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
          MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
          MAIL_FROM:             ${{ vars.MAIL_FROM }}   # "Sentiment Bot <bot@example.com>"
          MAIL_TO:               ${{ vars.MAIL_TO }}     # destination address
        run: |
          Rscript run_weekly_sentiment.R

      # 5 — (Optional) save the generated PDF + HTML as build artifacts
      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-sentiment-report
          path: |
            *.pdf
            *.html
