name: Weekly Twitter Sentiment Report

on:
  schedule:
    - cron: '30 8 * * MON'          # every Monday 08:30 UTC
  workflow_dispatch:                # manual trigger

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. System libraries required by various R packages
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ghostscript \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev

      # 3. Set up R
      - uses: r-lib/actions/setup-r@v2

      # 4. Install / restore R packages
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            tidyverse
            pagedown

      # 5. Run the weekly report pipeline
      - name: Run weekly sentiment script
        env:
          SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
          MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
          MAIL_FROM:             ${{ vars.MAIL_FROM }}
          MAIL_TO:               ${{ vars.MAIL_TO }}
        run: |
          Rscript run_weekly_sentiment.R

      # 6. Save PDF/HTML as artifacts (optional, but handy)
      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-sentiment-report
          path: |
            *.pdf
            *.html
